# Sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=300000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Battery
CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_POINTING=y
